apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - databases/postgresql-release.yaml
  - databases/mongodb-release.yaml
  - databases/redis-release.yaml
  - queues/kafka-release.yaml
  - queues/rabbitmq-release.yaml
