replicaCount: 1
image:
  repository: nginxdemos/hello
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80  # nginxdemos/hello использует порт 80
resources: {}  # Пока без ограничений ресурсов
