replicaCount: 1
image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80  # nginx слушает на 80
env:
  MONGO_URI: "mongodb://mongodb:27017"
  REDIS_HOST: "redis-master"
  KAFKA_BROKERS: "kafka:9092"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
